name: build

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.tsx'
  push:
    branches:
      - main
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.tsx'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [ 20 ]
    steps:
      - name: Running on ref
        run: echo ${{ github.ref }}
      - name: Upgrade distro
        run: sudo apt update
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install packages
        run: |
          pnpm install
      - name: Lint
        run: |
          pnpm lint
      - name: Build
        run: |
          pnpm build
      # - name: Test
      #   run: |
      #     pnpm test
