name: release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: macos-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [ 20 ]
    steps:
      - name: Running on ref
        run: echo ${{ github.ref }}
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install packages
        run: |
          pnpm install
      - name: Build distributables
        run: pnpm dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Draft release
        run: pnpm release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

